<x-layout-user>
    <div class="bg-white rounded-lg shadow-md p-6 mb-6">
        <div class="flex flex-col md:flex-row md:items-center md:justify-between mb-6">
            <h1 class="text-2xl font-bold text-gray-800 mb-4 md:mb-0">Pengembalian Ruangan</h1>
        </div>

        <!-- Enhanced Tab Navigation with Horizontal Scroll -->
        <div class="border-b border-gray-200 mb-6">
            <div class="relative pb-4">
                <!-- Scroll Left Button -->
                <button id="scrollLeft" class="absolute left-0 top-0 z-10 h-full w-8 bg-gradient-to-r from-white to-transparent flex items-center justify-center opacity-0 transition-opacity duration-300 md:hidden">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                    </svg>
                </button>

                <!-- Scroll Right Button -->
                <button id="scrollRight" class="absolute right-0 top-0 z-10 h-full w-8 bg-gradient-to-l from-white to-transparent flex items-center justify-center opacity-0 transition-opacity duration-300 md:hidden">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                    </svg>
                </button>

                <!-- Scrollable Tab Container -->
                <nav id="tabContainer" class="-mb-px flex overflow-x-auto scrollbar-hide scroll-smooth" style="scrollbar-width: none; -ms-overflow-style: none;">
                    <a href="{{ route('user.pengembalian.index', ['status' => 'semua']) }}" 
                       class="flex items-center whitespace-nowrap py-4 px-4 border-b-2 font-medium text-sm transition-colors duration-200 {{ $status === 'semua' || !$status ? 'border-blue-500 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300' }}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                        </svg>
                        Semua Pengembalian
                    </a>
                    <a href="{{ route('user.pengembalian.index', ['status' => 'belum_disetujui']) }}" 
                       class="flex items-center whitespace-nowrap py-4 px-4 border-b-2 font-medium text-sm transition-colors duration-200 {{ $status === 'belum_disetujui' ? 'border-blue-500 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300' }}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        Belum Disetujui
                    </a>
                    <a href="{{ route('user.pengembalian.index', ['status' => 'disetujui']) }}" 
                       class="flex items-center whitespace-nowrap py-4 px-4 border-b-2 font-medium text-sm transition-colors duration-200 {{ $status === 'disetujui' ? 'border-blue-500 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300' }}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        Disetujui
                    </a>
                </nav>

                <!-- Scroll Indicators (dots) -->
                <div id="scrollIndicators" class="flex justify-center mt-2 space-x-1 md:hidden">
                    <!-- Dots will be generated by JavaScript -->
                </div>
            </div>
        </div>

        <!-- Search -->
        <div class="mb-6">
            <div class="relative">
                <input
                    type="text"
                    id="searchInput"
                    placeholder="Cari berdasarkan nama ruangan..."
                    value="{{ $search ?? '' }}"
                    class="w-full px-4 py-2 border border-gray-300 rounded-md bg-white text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                >
                <div class="absolute inset-y-0 right-0 flex items-center pr-3">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                    </svg>
                </div>
            </div>
        </div>

        <!-- Flash Message -->
        @if (session('success'))
            <div id="flashMessage" class="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 mb-6 rounded">
                <div class="flex">
                    <div class="flex-shrink-0">
                        <svg class="h-5 w-5 text-green-500" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                        </svg>
                    </div>
                    <div class="ml-3">
                        <p class="text-sm">{{ session('success') }}</p>
                    </div>
                    <div class="ml-auto pl-3">
                        <div class="-mx-1.5 -my-1.5">
                            <button onclick="document.getElementById('flashMessage').remove()" class="inline-flex rounded-md p-1.5 text-green-500 hover:bg-green-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500">
                                <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        @endif

        <!-- Table Container -->
        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                    <tr>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            No
                        </th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Ruangan
                        </th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Tanggal Pinjam
                        </th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Tanggal Kembali
                        </th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Status
                        </th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Aksi
                        </th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    @forelse ($pengembalian ?? [] as $index => $item)
                        <tr class="hover:bg-gray-50">
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                {{ $index + 1 }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="text-sm font-medium text-gray-900">{{ $item->peminjaman->ruangan->nama_ruangan ?? 'Ruang Rapat Utama' }}</div>
                                <div class="text-xs text-gray-500">{{ $item->peminjaman->ruangan->lokasi ?? 'Lantai 2, Gedung A' }}</div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                {{ $item->peminjaman->tanggal ?? '25 Mei 2025' }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                {{ $item->tanggal_kembali ?? '25 Mei 2025' }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                @php
                                    $statusClass = [
                                        'belum_disetujui' => 'bg-yellow-100 text-yellow-800',
                                        'disetujui' => 'bg-green-100 text-green-800',
                                    ][$item->status ?? 'belum_disetujui'];
                                    
                                    $statusText = [
                                        'belum_disetujui' => 'Belum Disetujui',
                                        'disetujui' => 'Disetujui',
                                    ][$item->status ?? 'belum_disetujui'];
                                @endphp
                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full {{ $statusClass }}">
                                    {{ $statusText }}
                                </span>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                                <a href="{{ route('user.pengembalian.show', $item->id ?? 1) }}" class="text-blue-600 hover:text-blue-900" title="Detail">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                    </svg>
                                </a>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 text-center">
                                <div class="flex flex-col items-center justify-center py-8">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 text-gray-400 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                                    </svg>
                                    <p class="text-lg font-medium text-gray-900 mb-2">Tidak ada data pengembalian</p>
                                    <p class="text-gray-500">Anda belum memiliki riwayat pengembalian ruangan</p>
                                </div>
                            </td>
                        </tr>
                    @endforelse

                    <!-- Sample data when no real data is available -->
                    @if(empty($pengembalian))
                        <tr class="hover:bg-gray-50">
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                1
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="text-sm font-medium text-gray-900">Ruang Rapat Utama</div>
                                <div class="text-xs text-gray-500">Lantai 2, Gedung A</div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                25 Mei 2025
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                25 Mei 2025
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                    Disetujui
                                </span>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                                <a href="{{ route('user.pengembalian.show', 1) }}" class="text-blue-600 hover:text-blue-900" title="Detail">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                    </svg>
                                </a>
                            </td>
                        </tr>
                        <tr class="hover:bg-gray-50">
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                2
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="text-sm font-medium text-gray-900">Laboratorium Komputer</div>
                                <div class="text-xs text-gray-500">Lantai 1, Gedung B</div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                20 Mei 2025
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                20 Mei 2025
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800">
                                    Belum Disetujui
                                </span>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                                <a href="{{ route('user.pengembalian.show', 2) }}" class="text-blue-600 hover:text-blue-900" title="Detail">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                    </svg>
                                </a>
                            </td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>

        <!-- Pagination -->
        <div class="mt-4">
            <!-- Pagination links would go here -->
        </div>
    </div>

    <style>
        /* Hide scrollbar for Chrome, Safari and Opera */
        .scrollbar-hide::-webkit-scrollbar {
            display: none;
        }
        /* Hide scrollbar for IE, Edge and Firefox */
        .scrollbar-hide {
            -ms-overflow-style: none;  /* IE and Edge */
            scrollbar-width: none;  /* Firefox */
        }
        
        /* Smooth scroll behavior */
        .scroll-smooth {
            scroll-behavior: smooth;
        }
        
        /* Scroll indicator dots */
        .scroll-dot {
            width: 6px;
            height: 6px;
            border-radius: 50%;
            background-color: #d1d5db;
            transition: background-color 0.3s ease;
        }
        
        .scroll-dot.active {
            background-color: #3b82f6;
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const tabContainer = document.getElementById('tabContainer');
            const scrollLeftBtn = document.getElementById('scrollLeft');
            const scrollRightBtn = document.getElementById('scrollRight');
            const indicatorsContainer = document.getElementById('scrollIndicators');
            
            let isScrolling = false;
            let startX = 0;
            let scrollLeft = 0;

            // Check if scrolling is needed
            function checkScrollButtons() {
                if (window.innerWidth >= 768) { // md breakpoint
                    scrollLeftBtn.style.opacity = '0';
                    scrollRightBtn.style.opacity = '0';
                    return;
                }

                const canScrollLeft = tabContainer.scrollLeft > 0;
                const canScrollRight = tabContainer.scrollLeft < (tabContainer.scrollWidth - tabContainer.clientWidth);
                
                scrollLeftBtn.style.opacity = canScrollLeft ? '1' : '0';
                scrollRightBtn.style.opacity = canScrollRight ? '1' : '0';
                
                updateScrollIndicators();
            }

            // Create scroll indicators
            function createScrollIndicators() {
                if (window.innerWidth >= 768) return;
                
                const tabs = tabContainer.children;
                const totalTabs = tabs.length;
                const visibleTabs = Math.floor(tabContainer.clientWidth / tabs[0].offsetWidth);
                const totalDots = Math.max(1, totalTabs - visibleTabs + 1);
                
                indicatorsContainer.innerHTML = '';
                
                for (let i = 0; i < totalDots; i++) {
                    const dot = document.createElement('div');
                    dot.className = 'scroll-dot';
                    indicatorsContainer.appendChild(dot);
                }
                
                updateScrollIndicators();
            }

            // Update scroll indicators
            function updateScrollIndicators() {
                if (window.innerWidth >= 768) return;
                
                const dots = indicatorsContainer.children;
                if (dots.length === 0) return;
                
                const scrollPercentage = tabContainer.scrollLeft / (tabContainer.scrollWidth - tabContainer.clientWidth);
                const activeDotIndex = Math.round(scrollPercentage * (dots.length - 1));
                
                Array.from(dots).forEach((dot, index) => {
                    dot.classList.toggle('active', index === activeDotIndex);
                });
            }

            // Scroll functions
            function scrollTabsLeft() {
                const scrollAmount = tabContainer.clientWidth * 0.8;
                tabContainer.scrollBy({ left: -scrollAmount, behavior: 'smooth' });
            }

            function scrollTabsRight() {
                const scrollAmount = tabContainer.clientWidth * 0.8;
                tabContainer.scrollBy({ left: scrollAmount, behavior: 'smooth' });
            }

            // Event listeners
            scrollLeftBtn.addEventListener('click', scrollTabsLeft);
            scrollRightBtn.addEventListener('click', scrollTabsRight);
            
            tabContainer.addEventListener('scroll', checkScrollButtons);
            window.addEventListener('resize', () => {
                checkScrollButtons();
                createScrollIndicators();
            });

            // Touch/swipe support
            tabContainer.addEventListener('touchstart', (e) => {
                isScrolling = true;
                startX = e.touches[0].pageX - tabContainer.offsetLeft;
                scrollLeft = tabContainer.scrollLeft;
            });

            tabContainer.addEventListener('touchmove', (e) => {
                if (!isScrolling) return;
                e.preventDefault();
                const x = e.touches[0].pageX - tabContainer.offsetLeft;
                const walk = (x - startX) * 2;
                tabContainer.scrollLeft = scrollLeft - walk;
            });

            tabContainer.addEventListener('touchend', () => {
                isScrolling = false;
            });

            // Mouse drag support (optional)
            tabContainer.addEventListener('mousedown', (e) => {
                isScrolling = true;
                startX = e.pageX - tabContainer.offsetLeft;
                scrollLeft = tabContainer.scrollLeft;
                tabContainer.style.cursor = 'grabbing';
            });

            tabContainer.addEventListener('mousemove', (e) => {
                if (!isScrolling) return;
                e.preventDefault();
                const x = e.pageX - tabContainer.offsetLeft;
                const walk = (x - startX) * 2;
                tabContainer.scrollLeft = scrollLeft - walk;
            });

            tabContainer.addEventListener('mouseup', () => {
                isScrolling = false;
                tabContainer.style.cursor = 'grab';
            });

            tabContainer.addEventListener('mouseleave', () => {
                isScrolling = false;
                tabContainer.style.cursor = 'grab';
            });

            // Auto-scroll to active tab
            function scrollToActiveTab() {
                const activeTab = tabContainer.querySelector('.border-blue-500');
                if (activeTab) {
                    const containerRect = tabContainer.getBoundingClientRect();
                    const tabRect = activeTab.getBoundingClientRect();
                    
                    if (tabRect.left < containerRect.left || tabRect.right > containerRect.right) {
                        const scrollPosition = activeTab.offsetLeft - (tabContainer.clientWidth / 2) + (activeTab.clientWidth / 2);
                        tabContainer.scrollTo({ left: scrollPosition, behavior: 'smooth' });
                    }
                }
            }

            // Initialize
            checkScrollButtons();
            createScrollIndicators();
            scrollToActiveTab();
        });

        // Live search functionality
        const searchInput = document.getElementById('searchInput');
        let searchTimer;

        searchInput.addEventListener('input', function() {
            clearTimeout(searchTimer);
            searchTimer = setTimeout(performSearch, 500);
        });

        function performSearch() {
            const searchValue = searchInput.value;
            const currentStatus = '{{ $status ?? "semua" }}';
            
            window.location.href = `{{ route('user.pengembalian.index') }}?status=${currentStatus}&search=${searchValue}`;
        }

        // Close flash message after 5 seconds
        if (document.getElementById('flashMessage')) {
            setTimeout(() => {
                const flashMessage = document.getElementById('flashMessage');
                if (flashMessage) {
                    flashMessage.remove();
                }
            }, 5000);
        }
    </script>
</x-layout-user>
